spring:
  datasource:
    url: jdbc:sqlserver://localhost;
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      hibernate.ddl-auto: update