security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000
spring:
  datasource:
    url: jdbc:sqlserver://localhost;dataBase=BARBER;integratedSecurity=true;encrypt=true;trustServerCertificate=true
    username: root
    password: root
  jpa:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      hibernate.ddl-auto: update
      show-sql: true